apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-env-config
  namespace: task-api
data:
  # CORS configuration for GKE deployment - allow Ingress IP
  CORS_ALLOWED_ORIGINS: "http://136.110.145.6"
