apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: task-api
type: Opaque
data:
  # Base64 encoded values
  POSTGRES_USER: dXNlcg== # base64('user')
  POSTGRES_PASSWORD: cGFzc3dvcmQ= # base64('password')
  POSTGRES_DB_NAME: dGFza2Ri # base64('taskdb')
